%% Load TRMS model parameters
%
% This MATLAB script loads the nonlinear TRMS model parameters obtained by
% Tastemirov, Lecchini-Visintini and Morales (2017)
%
% MATLAB(R) file generated by MATLAB(R) 9.0
%
% (C) MIT License

%% Load system parameters to MATLAB workspace
TRMS.param.lm = 0.254;     % Length of main beam [m]
TRMS.param.lt = 0.275;     % Length of tail beam [m]
TRMS.param.Rm = 8;         % Main motor resistance [ohm]             
TRMS.param.Rt = 8;         % Tail motors resistance [ohm]            
TRMS.param.kvm = 0.0202;   % Main motor EMF constant [N.m.A^-1] 
TRMS.param.kvt = 0.0202;   % Main motor EMF constant [N.m.A^-1] 
TRMS.param.ktm = 0.0202;   % Tail motor EMF constant [V.rad^-1.s]
TRMS.param.ktt = 0.0202;   % Tail motor torque constant [V.rad^-1.s]
TRMS.param.kum = 8.5;      % Main motor’s input gain
TRMS.param.kut = 6.5;      % Tail motor’s input gain

TRMS.param.Im1 = 1.7249e-4;  % [Kg.m^2]
TRMS.param.It1 = 3.2170e-5;  % [Kg.m^2]
TRMS.param.Ipsi = 6.1644e-2; % [Kg.m^2]
TRMS.param.Iphi = 2.1117e-2; % [Kg.m^2]
TRMS.param.Ic = 8.3286e-2;   % [Kg.m^2]

TRMS.param.fvpsi = 4.2150e-4; % [N.m.rad^-1.s]
TRMS.param.fcpsi = 4.0548e-4; % [N.m]
TRMS.param.fvphi = 1.1243e-4; % [N.m.rad^-1.s]
TRMS.param.fcphi = 1.1758e-5; % [N.m]
TRMS.param.fvm = 4.1993e-6;   % [N.m.rad^-1.s]
TRMS.param.fvt = 3.2498e-6;   % [N.m.rad^-1.s]

TRMS.param.Ctm = (1.4971e-5 + 8.9974e-6)/2;  % [N.s^2.rad^-2]
TRMS.param.Ctt = (3.7755e-6 + 2.3046e-6)/2;  % [N.s^2.rad^-2]
TRMS.param.Crm = (5.0582e-7 + 4.5047e-7)/2;  % [N.s^2.rad^-2]
TRMS.param.Crt = (9.7031e-8 + 9.9176e-8)/2;  % [N.s^2.rad^-2]
TRMS.param.Cc = 9.8664e-3;                   % [N.m.rad^-1]

TRMS.param.Gz = -0.25254; % [N.m]
TRMS.param.Gy = 0.15032;  % [N.m]

TRMS.param.Hz = -1.9525e-3; % [Kg.m^2]
TRMS.param.Hy = 6.6120e-3;  % [Kg.m^2]