%% Load TRMS linearized model
%
% This MATLAB script:
% 1) Loads the nonlinear TRMS model based on the Euler-Lagrangian approach
% 2) Trims the model
% 3) Linearizes the system around the operating point
%
% MATLAB(R) file generated by MATLAB(R) 9.0 and Simulink Control Design (TM) 4.3
%
% (C) MIT License

%% Load system parameters, as provided by Tastemirov, Lecchini-Visintini and Morales (2017)
load_TRMS_Model_Parameters;

%% Search for a specified operating point for the model

%% Specify the model's name
model = 'trim_Lagrangian_Model_Nonlinear';

%% Create the operating point specification object
TRMS.trim.opspec = operspec(model);

%% Set the constraints on the states in the model
% - The defaults for all states are Known = false, SteadyState = true, Min = -Inf, and Max = Inf
% - Default model initial conditions are used to initialize optimization

TRMS.trim.opspec.States(1).Known = true;  % State (1) - Psi  
TRMS.trim.opspec.States(2).Known = true;  % State (2) - Psi_dot
TRMS.trim.opspec.States(3).Known = true;  % State (3) - Phi
TRMS.trim.opspec.States(4).Known = true;  % State (4) - Phi_dot
TRMS.trim.opspec.States(5).SteadyState = false;  % State (5) - Wm
TRMS.trim.opspec.States(6).SteadyState = false;  % State (6) - Wt

%% Set the constraints on the inputs in the model
% - The defaults for all inputs are Known = false, Min = -Inf, and Max = Inf
% - Default model initial conditions are used to initialize optimization

% Input (1) - Um
% Motors' control voltages range from -2.5V to 2.5V
% We set smaller voltages here in order to avoid trimming the model too close to the actuators' saturation 
TRMS.trim.opspec.Inputs(1).Min = -2;
TRMS.trim.opspec.Inputs(1).Max = 2;

% Input (2) - Ut
TRMS.trim.opspec.Inputs(2).Min = -2;
TRMS.trim.opspec.Inputs(2).Max = 2;

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and Max = Inf
% - Default model initial conditions are used to initialize optimization

%% Create the options
TRMS.trim.opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[TRMS.trim.op, TRMS.trim.opreport] = findop(model, TRMS.trim.opspec, TRMS.trim.opt);

%% Exact linearization of the Simulink model trim_Lagrangian_Model_Nonlinear

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
TRMS.trim.io = getlinio(model);

%% Linearize the model
TRMS.linear.sys = linearize(model, TRMS.trim.io, TRMS.trim.op);